#!/bin/bash
set -euo pipefail
set -x

echo "HOME" "$HOME" 
echo "GITHUB_JOB" "$GITHUB_JOB" 
echo "GITHUB_REF" "$GITHUB_REF" 
echo "GITHUB_SHA" "$GITHUB_SHA" 
echo "GITHUB_REPOSITORY" "$GITHUB_REPOSITORY" 
echo "GITHUB_REPOSITORY_OWNER" "$GITHUB_REPOSITORY_OWNER" 
echo "GITHUB_RUN_ID" "$GITHUB_RUN_ID" 
echo "GITHUB_RUN_NUMBER" "$GITHUB_RUN_NUMBER" 
echo "GITHUB_ACTOR" "$GITHUB_ACTOR" 
echo "GITHUB_WORKFLOW" "$GITHUB_WORKFLOW" 
echo "GITHUB_HEAD_REF" "$GITHUB_HEAD_REF" 
echo "GITHUB_BASE_REF" "$GITHUB_BASE_REF" 
echo "GITHUB_EVENT_NAME" "$GITHUB_EVENT_NAME" 
echo "GITHUB_SERVER_URL" "$GITHUB_SERVER_URL" 
echo "GITHUB_API_URL" "$GITHUB_API_URL" 
echo "GITHUB_GRAPHQL_URL" "$GITHUB_GRAPHQL_URL" 
echo "GITHUB_WORKSPACE" "$GITHUB_WORKSPACE" 
echo "GITHUB_ACTION" "$GITHUB_ACTION" 
echo "GITHUB_EVENT_PATH" "$GITHUB_EVENT_PATH" 
echo "RUNNER_OS" "$RUNNER_OS" 
echo "RUNNER_TOOL_CACHE" "$RUNNER_TOOL_CACHE" 
echo "RUNNER_TEMP" "$RUNNER_TEMP" 
echo "RUNNER_WORKSPACE" "$RUNNER_WORKSPACE" 
echo "ACTIONS_RUNTIME_URL" "$ACTIONS_RUNTIME_URL" 
echo "ACTIONS_RUNTIME_TOKEN" "$ACTIONS_RUNTIME_TOKEN" 
echo "ACTIONS_CACHE_URL" "$ACTIONS_CACHE_URL" 


ls -la

treebeard configure --api_key "$1" --project_id "$GITHUB_REPOSITORY_OWNER" 
treebeard run -n "$2" --confirm --watch
